services:
  - type: web
    name: mn-scraper-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DISPLAY
        value: :99
